### ISSUE TITLE
How to get the top-down map and the trajectory? 

### ISSUE THREAD

**Issue by lizixiaoboluo** [DefaultRui/BEV-Scene-Graph#3]
Hi, thanks for your great work.
Can you share how to get the top-down map and the corresponding trajectory like figure 4?
thank you very much！

**Comment by DefaultRui** [comment]
Hello! Actually, we drew it on powerpoint. First, we draw a top-down scatter plot of the coordinates. Then, The scatter plot was then manually mapped onto the top view.
